name: CI Workflow
on: [push, pull_request]
jobs:
  test:
    name: test
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x, 16.x]
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm i -g npm@8 && npm ci
      - name: Run linter
        run: npm run lint
      - name: Run tests
        run: npm test
